apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-1
data:
  {{- (.Files.Glob "conf/nginx/*").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-2
data:
  {{- (.Files.Glob "conf/nginx/conf.d/*").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-fpm-config-1
data:
  php.ini: |
{{- if eq .Values.global.env_name "prod" }}
{{ (.Files.Get "conf/php-fpm/php.ini-production") | indent 4 }}
{{- else }}
{{ (.Files.Get "conf/php-fpm/php.ini-development") | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-fpm-config-2
data:
  {{- (.Files.Glob "conf/php-fpm/php-fpm.d/*").AsConfig | nindent 2 }}
---
